version: '3.3'
services:
  onelist:
    restart: always
    build: # 这里会根据 Dockerfile 构建镜像
      context: .   # 构建上下文，指定为当前目录
      dockerfile: Dockerfile
    volumes:
      - '/root/onelist/config:/config'
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
