version: '3.3'
services:
  onelist:
    restart: always
    build: # 这里会根据 Dockerfile 构建镜像
      context: .   # 构建上下文，指定为当前目录
      dockerfile: Dockerfile
    volumes:
      - '/root/onelist/config:/config'
    ports:
      - '5245:5245'
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    extra_hosts:
      - 'api.themoviedb.org:13.224.161.90'
      - 'api.themoviedb.org:13.35.67.86'
      - 'api.themoviedb.org:13.249.175.212'
      - 'api.themoviedb.org:13.35.161.120'
      - 'image.themoviedb.org:104.16.61.155'
      - 'www.themoviedb.org:54.192.151.79'
